/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add_21 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [7:0] led,
    output reg [15:0] c,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  always @* begin
    c = 16'h0000;
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    sum = 16'h0000;
    led[6+1-:2] = 2'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
        v = (a[15+0-:1] & b[15+0-:1] & (~sum[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & sum[15+0-:1]);
      end
      2'h1: begin
        sum = a - b;
        v = (~a[15+0-:1] & b[15+0-:1] & sum[15+0-:1]) | ((a[15+0-:1]) & (~b[15+0-:1]) & ~sum[15+0-:1]);
      end
      2'h2: begin
        sum = a * b;
      end
      default: begin
        sum = 16'h0000;
      end
    endcase
    c = sum;
    z = (~|sum);
    n = sum[15+0-:1];
  end
endmodule
