/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_23 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] c
  );
  
  
  
  always @* begin
    c = 16'h0000;
    
    case (alufn[1+1-:2])
      2'h1: begin
        c[0+0-:1] = z;
      end
      2'h2: begin
        c[0+0-:1] = n ^ v;
      end
      2'h3: begin
        c[0+0-:1] = z | (n ^ v);
      end
    endcase
  end
endmodule
