/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module counter_2 (
    input clk,
    input rst,
    output reg [7:0] counter
  );
  
  
  
  reg [24:0] M_state_d, M_state_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    
    counter[0+7-:8] = M_state_q[18+6-:7];
    M_state_d = M_state_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
