/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux_2_29 (
    input [15:0] a,
    input [15:0] b,
    input sel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (sel)
      1'h0: begin
        out = a;
      end
      1'h1: begin
        out = b;
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
