/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux_3_27 (
    input [15:0] a,
    input [15:0] b,
    input [15:0] c,
    input [1:0] sel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (sel)
      2'h0: begin
        out = a;
      end
      2'h1: begin
        out = b;
      end
      2'h2: begin
        out = c;
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
