/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module register_35 (
    input clk,
    input rst,
    input [15:0] write,
    input [15:0] value,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] M_reg_d, M_reg_q = 1'h0;
  
  always @* begin
    M_reg_d = M_reg_q;
    
    
    case (write)
      1'h1: begin
        M_reg_d = value;
        out = M_reg_q;
      end
      1'h0: begin
        M_reg_d = M_reg_q;
        out = M_reg_q;
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_reg_q <= 1'h0;
    end else begin
      M_reg_q <= M_reg_d;
    end
  end
  
endmodule
