/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testRom_3 (
    input [23:0] io_dip,
    output reg [23:0] io_led
  );
  
  
  
  wire [16-1:0] M_myRom_out;
  reg [6-1:0] M_myRom_address;
  rom_4 myRom (
    .address(M_myRom_address),
    .out(M_myRom_out)
  );
  
  reg [1:0] level;
  
  reg [3:0] sequence;
  
  always @* begin
    io_led = 24'h000000;
    level = io_dip[16+4+1-:2];
    sequence = io_dip[16+0+3-:4];
    M_myRom_address = {level, sequence};
    io_led[16+0+5-:6] = {level, sequence};
    io_led[8+0+7-:8] = M_myRom_out[8+7-:8];
    io_led[0+0+7-:8] = M_myRom_out[0+7-:8];
  end
endmodule
